<?php
require_once __DIR__ . '/includes/database.php';
require_once __DIR__ . '/includes/layout.php';
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$statement = database()->prepare('SELECT * FROM menus WHERE id = :id AND stock > 0');
$statement->execute(['id' => $id]); $menu = $statement->fetch();
if (!$menu) { http_response_code(404); pageHeader('Menu introuvable'); echo '<main id="contenu" class="container py-5"><h1>Menu introuvable</h1><p>Ce menu n’est plus disponible.</p></main>'; pageFooter(); exit; }
pageHeader($menu['title']); ?>
<main id="contenu" class="container py-5"><a href="index.php#menus" class="link-secondary">← Retour aux menus</a><div class="row g-5 mt-1 align-items-start"><div class="col-lg-6"><img class="img-fluid rounded-4 detail-image" src="<?= htmlspecialchars($menu['image_url']) ?>" alt="Illustration du <?= htmlspecialchars($menu['title']) ?>"></div><section class="col-lg-6"><p class="eyebrow">Menu <?= htmlspecialchars($menu['theme']) ?></p><h1><?= htmlspecialchars($menu['title']) ?></h1><p class="lead"><?= htmlspecialchars($menu['description']) ?></p><div class="d-flex gap-2 mb-3"><span class="badge text-bg-light"><?= htmlspecialchars($menu['theme']) ?></span><span class="badge text-bg-success"><?= htmlspecialchars($menu['diet']) ?></span></div><dl class="detail-list"><dt>Composition</dt><dd>Une entrée, un plat et un dessert de saison.</dd><dt>Allergènes</dt><dd>Peut contenir gluten, lait, œufs et fruits à coque. Nous contacter pour une adaptation.</dd><dt>Conditions</dt><dd>Commande à effectuer au minimum 72 heures avant la prestation.</dd><dt>Disponibilité</dt><dd><?= (int) $menu['stock'] ?> commande(s) restante(s).</dd></dl><div class="price-box"><span>À partir de</span><strong><?= number_format($menu['price'], 2, ',', ' ') ?> € <small>/ personne</small></strong><span>Minimum <?= (int) $menu['min_people'] ?> personnes</span></div><a class="btn btn-primary btn-lg mt-4" href="order.php?menu_id=<?= (int) $menu['id'] ?>">Commander ce menu</a></section></div></main><?php pageFooter(); ?>
